// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChT5SgJSxIURoLJ2zxI8xSDtOHETI4Jn8',
    appId: '1:229195180845:web:b23ee5e83a00f376da81a4',
    messagingSenderId: '229195180845',
    projectId: 'agri-ai-20e34',
    authDomain: 'agri-ai-20e34.firebaseapp.com',
    storageBucket: 'agri-ai-20e34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSi9GI-Lz9TP4QipYWnfPanPofQXrJ5A',
    appId: '1:229195180845:android:208fdf50d259dcc5da81a4',
    messagingSenderId: '229195180845',
    projectId: 'agri-ai-20e34',
    storageBucket: 'agri-ai-20e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLmI2u2sF4lqL9jkZJOGGhZXXAQuEFzw',
    appId: '1:229195180845:ios:db7d652f9b7d433ada81a4',
    messagingSenderId: '229195180845',
    projectId: 'agri-ai-20e34',
    storageBucket: 'agri-ai-20e34.firebasestorage.app',
    iosBundleId: 'com.example.agriAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuLmI2u2sF4lqL9jkZJOGGhZXXAQuEFzw',
    appId: '1:229195180845:ios:db7d652f9b7d433ada81a4',
    messagingSenderId: '229195180845',
    projectId: 'agri-ai-20e34',
    storageBucket: 'agri-ai-20e34.firebasestorage.app',
    iosBundleId: 'com.example.agriAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChT5SgJSxIURoLJ2zxI8xSDtOHETI4Jn8',
    appId: '1:229195180845:web:23f023a4d47a8cd0da81a4',
    messagingSenderId: '229195180845',
    projectId: 'agri-ai-20e34',
    authDomain: 'agri-ai-20e34.firebaseapp.com',
    storageBucket: 'agri-ai-20e34.firebasestorage.app',
  );
}
