import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final pestAiServiceProvider = Provider((ref) => PestAiService());

class PestAiService {
  String get _apiKey => dotenv.env['GEMINI_API_KEY'] ?? '';

  GenerativeModel _getModel(String language, {String modelName = 'gemini-3.1-flash-lite'}) {
    String languageInstruction = 'Respond in English.';
    if (language == 'si') {
      languageInstruction = 'Respond ONLY in Sinhala script (සිංහල). Never use Romanized Singlish.';
    } else if (language == 'ta') {
      languageInstruction = 'Respond ONLY in Tamil script (தமிழ்). Never use Romanized Tanglish.';
    }

    return GenerativeModel(
      model: modelName,
      apiKey: _apiKey,
      systemInstruction: Content.system(
        'You are an expert Senior Agricultural Entomologist and Plant Pathologist specializing in tropical and Sri Lankan agriculture.\n'
        'When asked about pests, diseases, or crop protection for ANY crop:\n'
        '1. Language Policy: $languageInstruction\n'
        '2. Provide an exhaustive, highly structured, point-by-point guide with clear markdown headings and emojis:\n'
        '   ### 🐛 1. Major Insect Pests & Damage Symptoms (ප්‍රධාන කෘමි හානි හා ලක්ෂණ)\n'
        '   ### 🍄 2. Fungal, Bacterial & Viral Diseases (දිලීර, බැක්ටීරියා සහ වෛරස් රෝග)\n'
        '   ### 🌿 3. Immediate Organic & Biological Remedies (ස්වාභාවික හා කාබනික ප්‍රතිකාර)\n'
        '   ### 🧪 4. Recommended Chemical Controls & Dosages (රසායනික පාලනය හා නිර්දේශිත මාත්‍රා)\n'
        '   ### 🛡️ 5. Long-term Field Care & Preventive Practices (නැවත බෝවීම වැළැක්වීමේ උපදෙස්)\n'
        '3. Under each section, use clear bold bullet points (•) and highlight active ingredients, application times, and exact measurements.\n'
        '4. Keep advice highly practical, actionable, and tailored for farmers in the field.'
      ),
    );
  }

  Future<String> generatePestGuideForCrop({
    required String cropOrPestName,
    required String language,
  }) async {
    if (_apiKey.isEmpty) {
      throw Exception('Gemini API key is not configured in .env');
    }

    final prompt = 'Please provide an in-depth, comprehensive pest and disease management guide for the crop: "$cropOrPestName". Cover all major pests, symptoms, organic remedies, and chemical controls.';

    // Try primary model
    try {
      final model = _getModel(language, modelName: 'gemini-3.1-flash-lite');
      final response = await model.generateContent([Content.text(prompt)]);
      if (response.text != null && response.text!.isNotEmpty) {
        return response.text!;
      }
    } catch (e) {
      // Fallback model
      try {
        final fallbackModel = _getModel(language, modelName: 'gemini-3-flash-preview');
        final fallbackResponse = await fallbackModel.generateContent([Content.text(prompt)]);
        if (fallbackResponse.text != null && fallbackResponse.text!.isNotEmpty) {
          return fallbackResponse.text!;
        }
      } catch (fallbackError) {
        throw Exception('Failed to generate AI pest guide: $fallbackError');
      }
    }

    throw Exception('No response generated by AI model.');
  }

  Future<String> getInDepthPestAdvice({
    required String pestName,
    required String symptoms,
    required String crop,
    required String language,
  }) async {
    final prompt = 'Provide an in-depth emergency management protocol for the pest/disease "$pestName" affecting crop "$crop". Current symptoms: "$symptoms". Give step-by-step organic remedies, exact chemical dosages, spray schedule, and soil care.';
    return generatePestGuideForCrop(cropOrPestName: '$crop - $pestName: $prompt', language: language);
  }
}
